### ISSUE TITLE
VTR-L09 (P10) Times Out

### ISSUE THREAD

**Issue by ecrax** [mashed-potatoes/PotatoNV#102]
I don't know if this project is still being maintained, but maybe some have the same problem. I can connect my phone using the testpoint drivers and also start PotatoNV. But once it reaches the "Waiting for any device..." stage, I see in the Win Device Manager that the phone disconnects. Then Potato throws a timeout error.

![image](https://user-images.githubusercontent.com/53916931/140760707-99c31ffe-02c2-47f3-a5fb-19b9bbbfd610.png)

```
2021-11-08 15:28:13.449 | INFO     | PotatoNV v2.2.1
2021-11-08 15:28:13.452 | INFO     | User manual: https://kutt.it/pnv-en
2021-11-08 15:28:13.769 | DEBUG    | DownloadVCOM mode: COM6: HUAWEI USB COM 1.0
2021-11-08 15:28:19.995 | INFO     | PotatoNV v2.2.1
2021-11-08 15:28:20.010 | INFO     | User manual: https://kutt.it/pnv-en
2021-11-08 15:28:20.014 | INFO     | Verifying images...
2021-11-08 15:28:20.027 | DEBUG    | Opening COM6...
2021-11-08 15:28:20.030 | INFO     | Uploading hisi960...
2021-11-08 15:28:20.030 | INFO     | - xloader
2021-11-08 15:28:20.360 | INFO     | - uce
2021-11-08 15:28:20.767 | INFO     | - fastboot
2021-11-08 15:28:36.094 | INFO     | Waiting for any device...
2021-11-08 15:29:01.951 | ERROR    | Timeout error.
2021-11-08 15:29:01.956 | DEBUG    | at Potato.Fastboot.Fastboot.Wait()
    at PotatoNV_next.Core.Worker_DoWork(Object sender, DoWorkEventArgs e)
```

Any help is appreciated and if anyone needs more information, feel free to ask. :)

**Comment by mashed-potatoes** [comment]
@ecrax try to install HiSuite and Google USB Driver

**Comment by ecrax** [comment]
I have both installed
![image](https://user-images.githubusercontent.com/53916931/140765222-c2001a7d-e44c-4669-b4ed-e5caefba5b24.png)
![image](https://user-images.githubusercontent.com/53916931/140765275-129d2298-4a36-4574-90eb-153b2fe47775.png)

**Comment by mashed-potatoes** [comment]
@ecrax do you see any "Unrecognized device" in device manager?

**Comment by mashed-potatoes** [comment]
@ecrax start PotatoNV again, then check device manager again

**Comment by ecrax** [comment]
It seems like it gets completely disconnected, there is no unusual device in the device manager

**Comment by mashed-potatoes** [comment]
try to use USB 2.0 port or USB hub

**Comment by mashed-potatoes** [comment]
try USB 2.0 port / USB hub

**Comment by ecrax** [comment]
using a usb 2.0 port at the back of my computer worked, thanks a lot for your help and thanks for your work on PotatoNV :)
have a great day

**Comment by mashed-potatoes** [comment]
good luck
